version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cobrancas-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cobrancas
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: cobrancas-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: cobrancas-backend
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/cobrancas
      REDIS_HOST: redis
      REDIS_PORT: 6379
      BETTER_AUTH_SECRET: dev-secret-key-change-in-prod
      PORT: 3001
    ports:
      - '3001:3001'
    volumes:
      - ./apps/backend/src:/app/src
    command: npm run dev

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: cobrancas-frontend
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - '3000:3000'
    volumes:
      - ./apps/frontend/src:/app/src
    command: npm run dev

volumes:
  postgres_data:
  redis_data:
